### ISSUE TITLE
MacOS M1 Problem with Wrapper

### ISSUE THREAD

**Issue by SolarGuy8** [Desklop/RNNoise_Wrapper#15]
Traceback (most recent call last):
  File "/Users/art/PycharmProjects/rapfame-auto-mastering/app.py", line 174, in <module>
    main()
  File "/Users/art/PycharmProjects/rapfame-auto-mastering/app.py", line 135, in main
    denoiser_new = RNNoise()
  File "/Users/art/Library/Python/3.8/lib/python/site-packages/rnnoise_wrapper/rnnoise_wrapper.py", line 51, in __init__
    self.rnnoise_lib = ctypes.cdll.LoadLibrary(f_name_lib)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/art/Library/Python/3.8/lib/python/site-packages/rnnoise_wrapper/libs/librnnoise_5h_b_500k.so.0.4.1, 0x0006): tried: '/Users/art/Library/Python/3.8/lib/python/site-packages/rnnoise_wrapper/libs/librnnoise_5h_b_500k.so.0.4.1' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/art/Library/Python/3.8/lib/python/site-packages/rnnoise_wrapper/libs/librnnoise_5h_b_500k.so.0.4.1' (no such file), '/Users/art/Library/Python/3.8/lib/python/site-packages/rnnoise_wrapper/libs/librnnoise_5h_b_500k.so.0.4.1' (not a mach-o file)

**Comment by slezkinis** [comment]
Same problem

**Comment by Yessense** [comment]
You can check out the PR here: [PR #16 : Add macOS ARM64 compile script](https://github.com/dbklim/RNNoise_Wrapper/pull/16)
